### PR TITLE
FIX foreign key type error

### PR DESCRIPTION
**Pull request by srstrickland**
In Feb 2014, the following change was made to this repo:
    https://github.com/Tubular/peewee/commit/a60f596130a2cfcad1be15959e7d3bf8a4d44fa2

Most of this seems reasonable, except for the property override
(taken out here), which basically breaks the code at line 857:

```
super(ForeignKeyField, self).get_db_field()
```

So, if you have a ForeignKeyField that references a primary key in
another table, it will actually force peewee to think the foreign key
field is a primary key, rather than just the integer type that it should
be.

This is fairly innocuous, except for when we want to have peewee create
the tables for us, e.g. in testing.  As it is, it tries to generate
broken SQL:

```
CREATE TABLE `plans`
(
    `id` INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `branding` INTEGER AUTO_INCREMENT,  -- BAD!!!
    `created` INTEGER NOT NULL,
    `meta` LONGTEXT NOT NULL,
    FOREIGN KEY (`branding`) REFERENCES `branding` (`id`)
)
```

With this reverted as it is in this commit, the create-table generated
properly identifies the underlying field type of the foreign key.

### CODE REVIEW

**Comment by srstrickland** [comment]
Do you mean random solutions?  👍 

http://www.theonion.com/blogpost/sometimes-i-feel-like-im-the-only-one-trying-to-ge-11249

**Comment by yishengjiang99** [comment]
gg

On Wed, Oct 26, 2016 at 10:48 AM, Scott Strickland <notifications@github.com

**Comment by yishengjiang99** [comment]
I worked at TubularLabs years ago. Not sure if I should be on this thread.

**Comment by albertc1** [comment]
@yishengjiang99 Since this is a public repo, we don't have a lot of control over who gets emailed about changes.  I think it's up to you to stop following this repo on github to stop getting emails.

**Pull request merged**
